core/src/Entity/Framework/Mirror/Framework.php
<?php

namespace App\Entity\Framework\Mirror;

use App\Entity\Framework\LsDoc;
use App\Repository\Framework\Mirror\FrameworkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Swaggest\JsonDiff\JsonDiff;

#[ORM\Table(name: 'mirror_framework')]
#[ORM\Entity(repositoryClass: FrameworkRepository::class)]
class Framework
{
    final public const string STATUS_NEW = 'new';
    final public const string STATUS_SCHEDULED = 'scheduled';
    final public const string STATUS_PROCESSING = 'processing';
    final public const string STATUS_OK = 'ok';
    final public const string STATUS_ERROR = 'error';
    final public const string STATUS_SUSPENDED = 'suspended';

    final public const string ERROR_GENERAL = 'general';
    final public const string ERROR_ID_CONFLICT = 'identifier_conflict';

    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Server::class, inversedBy: 'frameworks')]
    #[ORM\JoinColumn(nullable: false)]
    private Server $server;

    #[ORM\Column(name: 'url', type: 'string', nullable: false)]
    private string $url = '';

    #[ORM\Column(name: 'identifier', type: 'string', nullable: false)]
    private string $identifier;

    #[ORM\Column(name: 'creator', type: 'string', nullable: true)]
    private ?string $creator = null;

    #[ORM\Column(name: 'title', type: 'string', nullable: true)]
    private ?string $title = null;

    #[ORM\OneToOne(mappedBy: 'mirroredFramework', targetEntity: LsDoc::class)]
    private ?LsDoc $framework = null;

    #[ORM\Column(name: 'visible', type: 'boolean', nullable: false, options: ['default' => true])]
    private bool $visible = true;

    #[ORM\Column(name: 'include', type: 'boolean', nullable: false)]
    private bool $include = true;

    #[ORM\Column(name: 'priority', type: 'integer', options: ['default' => 0])]
    private int $priority = 0;

    #[ORM\Column(name: 'status', type: 'string', options: ['default' => self::STATUS_NEW])]
    private string $status = self::STATUS_NEW;

    #[ORM\Column(name: 'status_count', type: 'integer', nullable: false, options: ['default' => 0])]
    private int $statusCount = 0;

    #[ORM\Column(name: 'last_check', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastCheck = null;

    #[ORM\Column(name: 'last_success', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastSuccess = null;

    #[ORM\Column(name: 'last_failure', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastFailure = null;

    #[ORM\Column(name: 'last_change', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastChange = null;

    #[ORM\Column(name: 'next_check', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $nextCheck = null;

    #[ORM\Column(name: 'error_type', type: 'string', nullable: true)]
    private ?string $errorType = null;

    #[ORM\Column(name: 'updated_at', type: 'datetime', precision: 6)]
    #[Gedmo\Timestampable(on: 'update')]
    private \DateTimeInterface $updatedAt;

    /**
     * @var string|resource|null
     */
    #[ORM\Column(name: 'last_content', type: 'blob', nullable: true)]
    private $lastContent;

    /**
     * @var string|resource|null
     */
    #[ORM\Column(name: 'last_success_content', type: 'blob', nullable: true)]
    private $lastSuccessContent;

    /**
     * @var Collection<array-key, Log>
     */
    #[ORM\OneToMany(mappedBy: 'mirror', targetEntity: Log::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $logs;

    public function __construct(Server $server, string $identifier)
    {
        $this->server = $server;
        $this->identifier = $identifier;
        $this->logs = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getServer(): Server
    {
        return $this->server;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    public function isInclude(): bool
    {
        return $this->include;
    }

    public function setInclude(bool $include): static
    {
        $this->include = $include;

        return $this;
    }

    public function getStatusCount(): int
    {
        return $this->statusCount;
    }

    public function getFramework(): ?LsDoc
    {
        return $this->framework;
    }

    public function setFramework(?LsDoc $framework): static
    {
        $this->framework = $framework;

        return $this;
    }

    public function getLastCheck(): ?\DateTimeInterface
    {
        return $this->lastCheck;
    }

    public function getLastChange(): ?\DateTimeInterface
    {
        return $this->lastChange;
    }

    public function getNextCheck(): ?\DateTimeInterface
    {
        return $this->nextCheck;
    }

    public function getErrorType(): ?string
    {
        return $this->errorType;
    }

    public function isIdConflicted(): bool
    {
        return static::STATUS_ERROR === $this->status && static::ERROR_ID_CONFLICT === $this->errorType;
    }

    public function setErrorType(?string $errorType): static
    {
        $this->errorType = $errorType;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function getTitle(): string
    {
        return $this->title ?? 'Unknown';
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCreator(): string
    {
        return $this->creator ?? 'Unknown';
    }

    public function setCreator(string $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    public function getLastSuccessContent(): ?string
    {
        if (null === $this->lastSuccessContent) {
            return null;
        }

        $uncompressed = false;

        if (is_string($this->lastSuccessContent)) {
            $uncompressed = bzdecompress($this->lastSuccessContent);
        }

        if (is_resource($this->lastSuccessContent)) {
            $uncompressed = bzdecompress(stream_get_contents($this->lastSuccessContent));
        }

        if (is_int($uncompressed) || false === $uncompressed) {
            return null;
        }

        return $uncompressed;
    }

    public function setLastSuccessContent(?string $lastSuccessContent): static
    {
        if (null === $lastSuccessContent) {
            $this->lastSuccessContent = null;
            $this->lastContent = null;

            return $this;
        }

        $this->lastSuccessContent = bzcompress($lastSuccessContent, 9);
        $this->lastContent = $this->lastSuccessContent;

        return $this;
    }

    public function getLastContent(): ?string
    {
        if (null === $this->lastContent) {
            return null;
        }

        $uncompressed = false;

        if (is_string($this->lastContent)) {
            $uncompressed = bzdecompress($this->lastContent);
        }

        if (is_resource($this->lastContent)) {
            $uncompressed = bzdecompress(stream_get_contents($this->lastContent));
        }

        if (is_int($uncompressed) || false === $uncompressed) {
            return null;
        }

        return $uncompressed;
    }

    public function setLastContent(?string $lastContent): static
    {
        if (null === $lastContent) {
            $this->lastContent = null;

            return $this;
        }

        $this->lastContent = bzcompress($lastContent, 9);

        return $this;
    }

    /**
     * @return Collection<array-key, Log>
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    public function addLog(string $status, string $message): Log
    {
        $log = new Log($this, $status, $message);
        $this->logs[] = $log;

        return $log;
    }

    public function clearLogs(): static
    {
        $this->logs->clear();

        return $this;
    }

    public function markToRefresh(): static
    {
        $this->nextCheck = new \DateTimeImmutable();
        $this->priority = 1000;
        $this->status = static::STATUS_SCHEDULED;

        return $this;
    }

    public function markSuccess(bool $changed = false): static
    {
        $this->errorType = null;
        $this->status = static::STATUS_OK;
        ++$this->statusCount;
        if ($changed || null === $this->lastSuccess || (null !== $this->lastFailure && $this->lastFailure > $this->lastSuccess)) {
            $this->statusCount = 1;
        }

        $this->lastSuccess = new \DateTimeImmutable();
        $this->lastCheck = $this->lastSuccess;
        $this->scheduleNextCheck($this->lastSuccess, (int) (86400 * 1.1855 ** min(20, $this->statusCount - 1)));

        if ($changed) {
            $this->lastChange = $this->lastSuccess;
        }

        return $this;
    }

    public function markFailure(?string $errorType = self::ERROR_GENERAL): static
    {
        $this->errorType = $errorType;
        $this->status = static::STATUS_ERROR;
        ++$this->statusCount;
        if (null === $this->lastFailure || (null !== $this->lastSuccess && $this->lastFailure < $this->lastSuccess)) {
            $this->statusCount = 1;
        }

        $this->lastFailure = new \DateTimeImmutable();
        $this->lastCheck = $this->lastFailure;
        $this->scheduleNextCheck($this->lastFailure, (int) (21600 * 1.5 ** min(12, $this->statusCount - 1)));

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

core/src/Controller/Mirror/FrameworkController.php
<?php

namespace App\Controller\Mirror;

use App\Entity\Framework\LsDoc;
use App\Entity\Framework\Mirror\Framework;
use App\Entity\Framework\Mirror\Log;
use App\Form\DTO\MirroredFrameworkDTO;
use App\Form\Type\MirroredFrameworkDTOType;
use App\Security\Permission;
use App\Service\MirrorServer;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route(path: '/admin/mirror/framework')]
#[IsGranted(Permission::MANAGE_MIRRORS)]
class FrameworkController extends AbstractController
{
    public function __construct(
        private readonly ManagerRegistry $managerRegistry,
    ) {
    }

    #[Route(path: '/new', name: 'mirror_framework_new')]
    public function new(Request $request, MirrorServer $mirrorService): Response
    {
        $frameworkDto = new MirroredFrameworkDTO();
        $form = $this->createForm(MirroredFrameworkDTOType::class, $frameworkDto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $framework = $mirrorService->addSingleFramework($frameworkDto);
                $server = $framework->getServer();

                return $this->redirectToRoute('mirror_server_list', ['id' => $server->getId()]);
            } catch (\Exception $e) {
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('mirror/framework/new.html.twig', [
            'mirrored_framework' => $frameworkDto,
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/{id}/resolve-id-conflict', name: 'mirror_framework_resolve_conflict')]
    public function resolveConflict(Request $request, Framework $framework): Response
    {
        $em = $this->managerRegistry->getManager();

        $doc = $em->getRepository(LsDoc::class)->findOneByIdentifier($framework->getIdentifier());
        if (null === $doc) {
            $this->addFlash('error', 'There is no conflict.');

            return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
        }

        $resolveForm = $this->createFrameworkResolveForm($framework);
        $resolveForm->handleRequest($request);

        if ($resolveForm->isSubmitted() && $resolveForm->isValid()) {
            $prevFramework = $doc->getMirroredFramework();
            if (null !== $prevFramework) {
                $prevFramework->setStatus(Framework::STATUS_ERROR);
                $prevFramework->markFailure(Framework::ERROR_ID_CONFLICT);
                $prevFramework->setInclude(false);
                $prevFramework->addLog(Log::STATUS_FAILURE, 'Another framework with the same identifier has been selected to be the mirror');
            }

            $doc->setMirroredFramework($framework);
            $doc->setOrg(null);
            $doc->setUser(null);
            $framework->setInclude(true);
            $framework->markToRefresh();

            foreach ($doc->getDocAcls() as $acl) {
                $em->remove($acl);
            }

            $em->flush();

            return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
        }

        return $this->render('mirror/framework/resolve.html.twig', [
            'frameworkToMirror' => $framework,
            'currentFramework' => $doc,
            'resolveForm' => $resolveForm->createView(),
        ]);
    }

    #[Route(path: '/{id}/refresh', name: 'mirror_framework_refresh', methods: ['POST'])]
    public function refresh(Framework $framework): Response
    {
        $framework->markToRefresh();
        $this->managerRegistry->getManager()->flush();

        return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
    }

    #[Route(path: '/{id}/enable', name: 'mirror_framework_enable', methods: ['POST'])]
    public function enable(Framework $framework): Response
    {
        $framework->setInclude(true);
        $framework->setStatus(Framework::STATUS_NEW);
        $framework->setErrorType(null);
        $framework->addLog(
            Log::STATUS_SUCCESS,
            'Mirroring was enabled'
        );
        $framework->markToRefresh();
        $this->managerRegistry->getManager()->flush();

        return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
    }

    #[Route(path: '/{id}/disable', name: 'mirror_framework_disable', methods: ['POST'])]
    public function disable(Framework $framework): Response
    {
        $framework->setInclude(false);
        if (null !== $framework->getFramework()) {
            $framework->getFramework()->setMirroredFramework(null);
            $framework->setStatus(Framework::STATUS_ERROR);
            $framework->setErrorType(Framework::ERROR_ID_CONFLICT);
            $framework->addLog(
                Log::STATUS_SUCCESS,
                'Mirroring was disabled, a framework now exists on the server with the same identifier'
            );
        }
        $this->managerRegistry->getManager()->flush();

        return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
    }

    #[Route(path: '/{id}/visible', name: 'mirror_framework_visible', methods: ['POST'])]
    public function visible(Framework $framework): Response
    {
        $framework->setVisible(true);
        $framework->addLog(
            Log::STATUS_SUCCESS,
            'Mirror was set to visible'
        );
        $this->managerRegistry->getManager()->flush();

        return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
    }

    #[Route(path: '/{id}/invisible', name: 'mirror_framework_invisible', methods: ['POST'])]
    public function invisible(Framework $framework): Response
    {
        $framework->setVisible(false);
        $framework->addLog(
            Log::STATUS_SUCCESS,
            'Mirror was set to invisible'
        );
        $this->managerRegistry->getManager()->flush();

        return $this->redirectToRoute('mirror_server_list', ['id' => $framework->getServer()->getId()]);
    }

    #[Route(path: '/{id}/logs', name: 'mirror_framework_logs')]
    public function viewLog(Framework $framework): Response
    {
        return $this->render('mirror/framework/logs.html.twig', [
            'framework' => $framework,
        ]);
    }

    private function createFrameworkResolveForm(Framework $framework): FormInterface
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('mirror_framework_resolve_conflict', ['id' => $framework->getId()]))
            ->getForm()
            ;
    }
}

core/templates/mirror/server/delete.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Remove Mirrored Server | {{ parent() }}{% endblock %}

{% block body %}
    <h1>Remove Server Information</h1>

    <div class="alert alert-danger">
        <p>
            This will remove all mirroring information for the server <q>{{ server.url }}</q>.
        </p>

        <p>
            The copies of the frameworks on the system will <strong>not</strong> be removed.
        </p>

        <p>
            Are you sure you wish to do this?
        </p>
        <div class="text-right">
            <a class="btn btn-primary" href="{{ path('mirror_server_index') }}">No, do not remove the server</a>
            {{ form_start(deleteForm, {'attr': {'class': 'form-inline-block'}}) }}
            <input class="btn btn-danger" type="submit" value="Yes, remove all server information" />
            {{ form_end(deleteForm) }}
        </div>
    </div>
{% endblock %}

core/templates/mirror/server/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Mirrored Server | {{ parent() }}{% endblock %}

{% block body %}
    <h1>Edit Mirrored Server</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="form-group">
        <span class="col-sm-2"></span>
        <div class="col-sm-10">
            Go to <a href="{{ path('oauth_credentials_index') }}">Manage OAuth Credentials</a> to add new credentials.
        </div>

        <div class="form-group">
            <div class="col-sm-12 text-right">
                <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
            </div>
        </div>
    </div>
    {{ form_end(form) }}

    <div class="text-right">
        <a href="{{ path('mirror_server_index') }}">back to list</a>
    </div>
{% endblock %}

core/templates/mirror/server/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mirrored Server List | {{ parent() }}{% endblock %}

{% block body %}
    <h1>Mirrored Servers</h1>

    <p>
        <a class="btn btn-default" href="{{ path('mirror_server_add') }}">Add Mirrored Server</a>
        <a class="btn btn-default" href="{{ path('mirror_framework_new') }}">Add Single Mirrored Framework</a>
    </p>

    <div class="row mirrored-server-view" id="mirroredServerView">
        <div class="col-sm-12">
            <table id="mirroredServerTable" class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Server</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for server in servers %}
                        <tr>
                            <td class="status">
                                {% for name, val in statuses[server.id] %}
                                    {% if val != 0 %}
                                        {% if name == 'new' %}
                                            <i class="fa fa-star" title="New: {{ val }}" aria-label="New"></i> {{ val }} &nbsp;
                                        {% elseif name == 'ok' %}
                                            <i class="fa fa-check-circle" title="Okay: {{ val }}" aria-label="Okay"></i> {{ val }} &nbsp;
                                        {% elseif name == 'scheduled' %}
                                            <i class="fa fa-calendar-check-o" title="Scheduled: {{ val }}" aria-label="Scheduled"></i> {{ val }} &nbsp;
                                        {% elseif name == 'processing' %}
                                            <i class="fa fa-refresh fa-spin" title="Processing: {{ val }}" aria-label="Processing"></i> {{ val }} &nbsp;
                                        {% elseif name == 'error' %}
                                            <i class="fa fa-warning" title="Error: {{ val }}" aria-label="Error"></i> {{ val }} &nbsp;
                                        {% elseif name == 'not-included' %}
                                            <i class="fa fa-minus-circle" title="Excluded: {{ val }}" aria-label="Excluded"></i> {{ val }} &nbsp;
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{{ path('mirror_server_list', {'id': server.id}) }}">{{ server.url }}</a>
                            </td>
                            <td>
                                <a class="btn btn-primary" href="{{ path('mirror_server_list', {'id': server.id}) }}">View Frameworks</a>
                                <a class="btn btn-default" href="{{ path('mirror_server_edit', {'id': server.id}) }}">Edit</a>
                                <a class="btn btn-danger" href="{{ path('mirror_server_delete', {'id': server.id}) }}">Remove Server</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $(function() {

        })
    </script>
{% endblock %}

core/templates/mirror/server/list.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ server.url }} framework list | {{ parent() }}{% endblock %}

{% block body %}
    <h1>List of frameworks from {{ server.url }}</h1>

    <div class="row">
        <span class="text-left col-sm-6">
            List last updated {{ server.lastCheck|date('Y-m-d H:i:s') }}
        </span>
        <span class="text-right col-sm-6">
            {{ form_start(serverRefreshForm, {'attr': {'class': 'form-inline-block'}}) }}
            <input class="btn btn-default" type="submit" value="Refresh" />
            {{ form_end(serverRefreshForm) }}
            <a class="btn btn-primary" href="{{ path('mirror_server_index') }}">View server list</a>
        </span>
    </div>
    <p></p>

    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Status</th>
                <th>Framework</th>
                <th>Last Check</th>
                <th>Last Change</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for framework in server.frameworks|sort((a, b) => (a.creator <=> b.creator) ?: (a.title <=> b.title)) %}
                <tr>
                    <td class="status">
                        {%- if framework.include -%}
                            {% if framework.status == 'new' %}
                                <i class="fa fa-star" title="New" aria-label="New"></i>
                            {% elseif framework.status == 'ok' %}
                                <i class="fa fa-check-circle" title="Okay" aria-label="Okay"></i>
                            {% elseif framework.status == 'scheduled' %}
                                <i class="fa fa-calendar-check-o" title="Scheduled" aria-label="Scheduled"></i>
                            {% elseif framework.status == 'processing' %}
                                <i class="fa fa-refresh fa-spin" title="Processing" aria-label="Processing"></i>
                            {% elseif framework.status == 'error' %}
                                <i class="fa fa-warning" title="Error" aria-label="Error"></i>
                            {% endif %}
                        {%- else -%}
                            <i class="fa fa-minus-circle" title="Excluded" aria-label="Excluded"></i>
                        {%- endif -%}
                    </td>
                    <td>
                        <span title="{{ framework.identifier }}">{{ framework.creator }} / {{ framework.title }}</span>
                        {% if framework.framework is not null %}
                            <a href="{{ path('doc_tree_view', {'slug': framework.framework.slug}) }}"><i class="fa fa-external-link" title="Go to document view" aria-label="Go to document view"></i></a>
                        {% endif %}
                    </td>
                    <td>{{ framework.lastCheck ? framework.lastCheck|date('Y-m-d H:i') : '-' }}</td>
                    <td>{{ framework.lastChange ? framework.lastChange|date('Y-m-d H:i') : '-' }}</td>
                    <td>
                        {% if showLogs[framework.id] is defined %}
                            <a class="btn btn-default {% if framework.include and framework.status == 'error' %}btn-warning{% endif %}" href="{{ showLogs[framework.id] }}">Show Logs</a>
                        {% endif %}

                        {% if framework.idConflicted %}
                            <a class="btn btn-primary" href="{{ path('mirror_framework_resolve_conflict', {'id': framework.id}) }}">Resolve ID Conflict</a>
                        {% else %}
                            {% if visibleForms[framework.id] is defined %}
                                {{ form_start(visibleForms[framework.id], {'attr': {'class': 'form-inline-block'}}) }}
                                <input class="btn btn-default" type="submit" value="{{  framework.visible ?  'Make Invisible' : 'Make Visible' }}" />
                                {{ form_end(visibleForms[framework.id]) }}
                            {% endif %}

                            {% if refreshForms[framework.id] is defined and framework.status != 'scheduled' %}
                                {{ form_start(refreshForms[framework.id], {'attr': {'class': 'form-inline-block'}}) }}
                                <input class="btn btn-default" type="submit" value="Refresh" />
                                {{ form_end(refreshForms[framework.id]) }}
                            {% endif %}

                            {% if enableForms[framework.id] is defined %}
                                {{ form_start(enableForms[framework.id], {'attr': {'class': 'form-inline-block'}}) }}
                                <input class="btn btn-default" type="submit" value="Start Mirroring" />
                                {{ form_end(enableForms[framework.id]) }}
                            {% endif %}

                            {% if disableForms[framework.id] is defined %}
                                {{ form_start(disableForms[framework.id], {'attr': {'class': 'form-inline-block'}}) }}
                                <input class="btn btn-default" type="submit" value="Stop Mirroring" />
                                {{ form_end(disableForms[framework.id]) }}
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

core/templates/mirror/server/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Add Mirrored Server | {{ parent() }}{% endblock %}

{% block body %}
    <h1>Add New Mirrored Server</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="form-group">
            <span class="col-sm-2"></span>
            <div class="col-sm-10">
                Go to <a href="{{ path('oauth_credentials_index') }}">Manage OAuth Credentials</a> to add new credentials.
            </div>

            <div class="form-group">
                <div class="col-sm-12 text-right">
                    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
                </div>
            </div>
        </div>
    {{ form_end(form) }}

    <div class="text-right">
        <a href="{{ path('mirror_server_index') }}">back to list</a>
    </div>
{% endblock %}