core/src/Entity/Framework/AbstractLsBase.php
<?php

namespace App\Entity\Framework;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\MappedSuperclass]
class AbstractLsBase implements IdentifiableInterface
{
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    #[ORM\Column(name: 'identifier', type: 'string', length: 300, unique: true, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Uuid(strict: false)]
    #[Assert\Length(max: 300)]
    protected ?string $identifier = null;

    #[ORM\Column(name: 'uri', type: 'string', length: 300, unique: true, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 300)]
    protected ?string $uri = null;

    #[ORM\Column(name: 'extra', type: 'json', nullable: true)]
    protected ?array $extra = null;

    #[ORM\Column(name: 'changed_at', type: 'datetime', precision: 6)]
    #[Gedmo\Timestampable(on: 'update')]
    private \DateTimeInterface $changedAt;

    #[ORM\Column(name: 'updated_at', type: 'datetime', precision: 6)]
    #[Gedmo\Timestampable(on: 'update')]
    protected \DateTimeInterface $updatedAt;

    public function __construct(UuidInterface|string|null $identifier = null)
    {
        if ($identifier instanceof UuidInterface) {
            $identifier = strtolower($identifier->toString());
        } elseif (is_string($identifier) && Uuid::isValid($identifier)) {
            $identifier = strtolower(Uuid::fromString($identifier)->toString());
        } else {
            $identifier = Uuid::uuid1()->toString();
        }

        $this->identifier = $identifier;
        $this->uri = 'local:'.$this->identifier;

        $this->updatedAt = new \DateTimeImmutable();
        $this->changedAt = $this->updatedAt;
    }

    public function __clone()
    {
        // Clear values for new item
        $this->id = null;

        // Generate a new identifier
        $identifier = Uuid::uuid1()->toString();
        $this->identifier = $identifier;
        $this->uri = 'local:'.$this->identifier;

        // Set last change/update to now
        $this->updatedAt = new \DateTimeImmutable();
        $this->changedAt = $this->updatedAt;
    }

    /**
     * Get the internal id of the object (or null if not persisted).
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @throws \InvalidArgumentException
     */
    public function setIdentifier(UuidInterface|string $identifier): static
    {
        // If the identifier is in the form of a UUID then lower case it
        if ($identifier instanceof UuidInterface) {
            $identifier = strtolower($identifier->toString());
        } elseif (Uuid::isValid($identifier)) {
            $identifier = strtolower(Uuid::fromString($identifier)->toString());
        } else {
            throw new \InvalidArgumentException('The identifier must be a UUID.');
        }

        $this->identifier = $identifier;

        return $this;
    }

    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    public function setUri(string $uri): static
    {
        $this->uri = $uri;

        return $this;
    }

    public function getUri(): string
    {
        return $this->uri;
    }

    public function setChangedAt(\DateTimeInterface $changedAt): static
    {
        $this->changedAt = $changedAt;

        return $this;
    }

    public function getChangedAt(): \DateTimeInterface
    {
        return $this->changedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function getExtra(): array
    {
        return $this->extra ?? [];
    }

    public function setExtra(?array $extra): static
    {
        $this->extra = $extra;

        return $this;
    }

    public function getExtraProperty(string $property): mixed
    {
        return $this->extra[$property] ?? null;
    }

    public function setExtraProperty(string $property, mixed $value): static
    {
        if (null === $this->extra && null === $value) {
            return $this;
        }

        if (null === $value) {
            unset($this->extra[$property]);
        } else {
            $this->extra[$property] = $value;
        }

        return $this;
    }
}

core/src/Entity/Framework/AbstractLsDefinition.php
<?php

namespace App\Entity\Framework;

use Doctrine\ORM\Mapping as ORM;

#[ORM\MappedSuperclass]
class AbstractLsDefinition extends AbstractLsBase
{
    #[ORM\Column(name: 'title', type: 'string', length: 1024, nullable: true)]
    protected ?string $title = null;

    #[ORM\Column(name: 'description', type: 'text', nullable: true)]
    protected ?string $description = null;

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDescriptionOrNull(): ?string
    {
        return $this->description;
    }

    public function getDescription(): ?string
    {
        return $this->description ?? $this->title;
    }
}

core/src/Entity/Framework/AccessAdditionalFieldTrait.php
<?php

namespace App\Entity\Framework;

trait AccessAdditionalFieldTrait
{
    abstract public function getExtraProperty(string $property): mixed;

    abstract public function setExtraProperty(string $property, mixed $value);

    public function getAdditionalFields(): array
    {
        return $this->getExtraProperty('customFields') ?? [];
    }

    public function setAdditionalFields(array $values): void
    {
        foreach ($values as $key => $value) {
            if (null === $value) {
                unset($values[$key]);
            }
        }

        if ([] === $values) {
            $this->setExtraProperty('customFields', null);

            return;
        }

        $this->setExtraProperty('customFields', $values);
    }

    public function getAdditionalField(string $name)
    {
        $customFields = $this->getExtraProperty('customFields') ?? [];

        return $customFields[$name] ?? null;
    }

    public function setAdditionalField(string $name, mixed $value): void
    {
        $customFields = $this->getExtraProperty('customFields') ?? [];

        $customFields[$name] = $value;
        if (null === $value) {
            unset($customFields[$name]);
        }

        if ([] === $customFields) {
            $this->setExtraProperty('customFields', null);

            return;
        }

        $this->setExtraProperty('customFields', $customFields);
    }
}

core/src/Entity/Framework/CaseApiInterface.php
<?php

namespace App\Entity\Framework;

/**
 * Interface CaseApiInterface
 *
 * Identifies objects that are exposed via the CASE API
 */
interface CaseApiInterface extends IdentifiableInterface
{
    public function getUpdatedAt(): \DateTimeInterface;
}

core/src/Entity/Framework/IdentifiableInterface.php
<?php

namespace App\Entity\Framework;

interface IdentifiableInterface
{
    public function getIdentifier(): string;

    public function getUri(): string;
}

core/src/Entity/Framework/LsDoc.php
<?php

namespace App\Entity\Framework;

use App\Entity\Framework\Mirror\Framework;
use App\Entity\LockableInterface;
use App\Entity\User\Organization;
use App\Entity\User\User;
use App\Entity\User\UserDocAcl;
use App\Repository\Framework\LsDocRepository;
use App\Util\Compare;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'ls_doc')]
#[ORM\Entity(repositoryClass: LsDocRepository::class)]
#[UniqueEntity('uri')]
#[UniqueEntity('urlName')]
#[UniqueEntity('identifier')]
class LsDoc extends AbstractLsBase implements CaseApiInterface, LockableInterface
{
    final public const string ADOPTION_STATUS_PRIVATE_DRAFT = 'Private Draft';
    final public const string ADOPTION_STATUS_DRAFT = 'Draft';
    final public const string ADOPTION_STATUS_ADOPTED = 'Adopted';
    final public const string ADOPTION_STATUS_DEPRECATED = 'Deprecated';

    #[ORM\ManyToOne(targetEntity: Organization::class, inversedBy: 'frameworks')]
    #[ORM\JoinColumn(name: 'org_id', referencedColumnName: 'id', nullable: true)]
    #[Assert\Type(Organization::class)]
    protected ?Organization $org = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'frameworks')]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: true)]
    #[Assert\Type(User::class)]
    protected ?User $user = null;

    #[ORM\Column(name: 'official_uri', type: 'string', length: 300, nullable: true)]
    #[Assert\Length(max: 300)]
    #[Assert\Url(requireTld: true)]
    private ?string $officialUri = null;

    #[ORM\Column(name: 'creator', type: 'string', length: 300, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 300)]
    private ?string $creator = null;

    #[ORM\Column(name: 'publisher', type: 'string', length: 300, nullable: true)]
    #[Assert\Length(max: 300)]
    private ?string $publisher = null;

    #[ORM\Column(name: 'title', type: 'string', length: 120, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 120)]
    private ?string $title = null;

    #[ORM\Column(name: 'url_name', type: 'string', length: 255, unique: true, nullable: true)]
    #[Assert\Length(max: 10)]
    #[Assert\Regex(pattern: '/^\d+$/', message: 'The URL Name cannot be a number.', match: false)]
    #[Assert\Regex(pattern: '/^[a-zA-Z0-9.-]+$/', message: 'The URL Name can only use alpha-numeric characters plus a period (.) or dash (-).')]
    private ?string $urlName = null;

    #[ORM\Column(name: 'version', type: 'string', length: 50, nullable: true)]
    #[Assert\Length(max: 50)]
    private ?string $version = null;

    #[ORM\Column(name: 'description', type: 'string', length: 300, nullable: true)]
    #[Assert\Length(max: 300)]
    private ?string $description = null;

    /**
     * @var string[]|null
     */
    #[ORM\Column(name: 'subject', type: 'json', nullable: true)]
    #[Assert\All([new Assert\Type('string')])]
    private ?array $subject = [];

    /**
     * @var Collection<array-key, LsDefSubject>
     */
    #[ORM\ManyToMany(targetEntity: LsDefSubject::class)]
    #[ORM\JoinTable(name: 'ls_doc_subject')]
    #[ORM\JoinColumn(name: 'ls_doc_id', referencedColumnName: 'id')]
    #[ORM\InverseJoinColumn(name: 'subject_id', referencedColumnName: 'id')]
    #[Assert\All([new Assert\Type(LsDefSubject::class)])]
    private Collection $subjects;

    #[ORM\Column(name: 'language', type: 'string', length: 10, nullable: true)]
    #[Assert\Length(max: 10)]
    private ?string $language = null;

    #[ORM\Column(name: 'adoption_status', type: 'string', length: 50, nullable: true)]
    #[Assert\Length(max: 50)]
    #[Assert\Choice(callback: 'getStatuses')]
    private ?string $adoptionStatus = null;

    #[ORM\Column(name: 'status_start', type: 'date', nullable: true)]
    private ?\DateTimeInterface $statusStart = null;

    #[ORM\Column(name: 'status_end', type: 'date', nullable: true)]
    private ?\DateTimeInterface $statusEnd = null;

    #[ORM\ManyToOne(targetEntity: LsDefLicence::class)]
    #[ORM\JoinColumn(name: 'licence_id', referencedColumnName: 'id', nullable: true)]
    private ?LsDefLicence $licence = null;

    #[ORM\ManyToOne(targetEntity: FrameworkType::class, cascade: ['persist'])]
    #[ORM\JoinColumn(name: 'frameworktype_id', referencedColumnName: 'id', nullable: true)]
    private ?FrameworkType $frameworkType = null;

    #[ORM\Column(name: 'note', type: 'text', nullable: true)]
    private ?string $note = null;

    /**
     * @var Collection<array-key, LsItem>
     */
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: LsItem::class, fetch: 'EXTRA_LAZY', indexBy: 'id')]
    #[Assert\All([new Assert\Type(LsItem::class)])]
    private Collection $lsItems;

    /**
     * @var Collection<array-key, LsAssociation>
     */
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: LsAssociation::class, fetch: 'EXTRA_LAZY', indexBy: 'id')]
    #[Assert\All([new Assert\Type(LsAssociation::class)])]
    private Collection $docAssociations;

    /**
     * @var Collection<array-key, LsAssociation>
     */
    #[Assert\All([new Assert\Type(LsAssociation::class)])]
    #[ORM\OneToMany(mappedBy: 'originLsDoc', targetEntity: LsAssociation::class, cascade: ['persist'], indexBy: 'id')]
    private Collection $associations;

    /**
     * @var Collection<array-key, LsAssociation>
     */
    #[Assert\All([new Assert\Type(LsAssociation::class)])]
    #[ORM\OneToMany(mappedBy: 'destinationLsDoc', targetEntity: LsAssociation::class, cascade: ['persist'], indexBy: 'id')]
    private Collection $inverseAssociations;

    /**
     * @var Collection<array-key, LsDocAttribute>
     */
    #[Assert\All([new Assert\Type(LsDocAttribute::class)])]
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: LsDocAttribute::class, cascade: ['ALL'], orphanRemoval: true, indexBy: 'attribute')]
    private Collection $attributes;

    /**
     * @var Collection<array-key, UserDocAcl>
     */
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: UserDocAcl::class, fetch: 'EXTRA_LAZY', indexBy: 'user')]
    #[Assert\All([new Assert\Type(UserDocAcl::class)])]
    protected Collection $docAcls;

    /**
     * @var Collection<array-key, ImportLog>
     */
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: ImportLog::class, fetch: 'EXTRA_LAZY', indexBy: 'lsDoc')]
    #[Assert\All([new Assert\Type(ImportLog::class)])]
    protected Collection $importLogs;

    /**
     * @var Collection<array-key, LsDefAssociationGrouping>
     */
    #[ORM\OneToMany(mappedBy: 'lsDoc', targetEntity: LsDefAssociationGrouping::class, fetch: 'EXTRA_LAZY', indexBy: 'id')]
    #[Assert\All([new Assert\Type(LsDefAssociationGrouping::class)])]
    protected Collection $associationGroupings;

    #[Assert\Choice(['organization', 'user'])]
    protected ?string $ownedBy = null;

    #[ORM\OneToOne(inversedBy: 'framework', targetEntity: Framework::class)]
    private ?Framework $mirroredFramework = null;

    public function __construct(UuidInterface|string|null $identifier = null)
    {
        parent::__construct($identifier);

        $this->lsItems = new ArrayCollection();
        $this->docAssociations = new ArrayCollection();
        $this->associations = new ArrayCollection();
        $this->inverseAssociations = new ArrayCollection();
        $this->attributes = new ArrayCollection();
        $this->subjects = new ArrayCollection();
        $this->docAcls = new ArrayCollection();
        $this->importLogs = new ArrayCollection();
        $this->associationGroupings = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getUri();
    }

    /**
     * Get the list of Adoption Statuses.
     */
    public static function getStatuses(): array
    {
        return [
            static::ADOPTION_STATUS_PRIVATE_DRAFT,
            static::ADOPTION_STATUS_DRAFT,
            static::ADOPTION_STATUS_ADOPTED,
            static::ADOPTION_STATUS_DEPRECATED,
        ];
    }

    /**
     * Get the list of Adoption Statuses where editing is allowed.
     */
    public static function getEditableStatuses(): array
    {
        return [
            static::ADOPTION_STATUS_PRIVATE_DRAFT,
            static::ADOPTION_STATUS_DRAFT,
        ];
    }

    public function isDraft(): bool
    {
        if (null === $this->adoptionStatus || '' === $this->adoptionStatus) {
            return true;
        }

        return in_array($this->adoptionStatus, static::getEditableStatuses(), true);
    }

    public function isAdopted(): bool
    {
        return $this->adoptionStatus === static::ADOPTION_STATUS_ADOPTED;
    }

    public function isDeprecated(): bool
    {
        return $this->adoptionStatus === static::ADOPTION_STATUS_DEPRECATED;
    }

    public function setOfficialUri(?string $officialUri): static
    {
        $this->officialUri = $officialUri;

        return $this;
    }

    public function getOfficialUri(): ?string
    {
        return $this->officialUri;
    }

    public function setCreator(?string $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setPublisher(?string $publisher): static
    {
        $this->publisher = $publisher;

        return $this;
    }

    public function getPublisher(): ?string
    {
        return $this->publisher;
    }

    public function setTitle(string $title): static
    {
        $this->title = mb_substr($title, 0, 120);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getShortStatement(): string
    {
        return mb_substr($this->title ?? 'Unknown', 0, 60);
    }

core/templates/framework/editor/_full_screen_modal_component.html.twig
{% if closeButton is not defined %}
    {% set closeButton = 'Close' %}
{% endif %}
{% if saveButton is not defined %}
    {% set saveButton = 'Save' %}
{% endif %}
<div class="modal fade" id="{{ modalName }}Modal" tabindex="-1" role="dialog" aria-labelledby="{{ modalName }}ModalLabel">
    <div class="modal-dialog modal-xl" role="document" style="width:99%">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="{{ modalName }}ModalLabel">{{ modalTitle }}</h4>
                <button type="button" class="close btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% block modalBody %}Loading form...{% endblock %}
            </div>
            <div class="modal-footer">
                {% block modalAllButtons %}
                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">{{ closeButton }}</button>
                    {% block modalButtons %}
                        <button type="button" class="btn btn-primary btn-save">{{ saveButton }}</button>
                    {% endblock %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

core/templates/framework/editor/_ls_association_component.html.twig
{% if items is not empty %}
    <section class="card card-default card-component item-component" id="item-component-{{ componentName }}">
        <div class="card-header">{{ title }}</div>
        <div class="card-body">
            <div>
                <div class="list-group">
                    {% for association in items %}
                        {% if association.destinationLsItem is defined %}
                            {% if association.destinationLsItem is not empty %}
                                {% if viewingItem == association.destinationLsItem %}
                                    {% set item = association.originLsItem %}
                                {% else %}
                                    {% set item = association.destinationLsItem %}
                                {% endif %}
                                <a href="{{ path('editor_lsitem', {'id':item.id}) }}" data-item-id="{{ item.id }}" data-association-id="{{ association.id }}" class="list-group-item lsassociation lsitem clearfix">
                                    {% block start_of_item_a '' %}
                                    {% if item.humanCodingScheme is not empty %}
                                        <span class="item-humanCodingScheme">{{ item.humanCodingScheme }}</span>
                                    {% endif %}
                                    {% if item.fullStatement != item.humanCodingScheme %}
                                        {{ item.fullStatement }}
                                    {% endif %}
                                    {% if item.lsDoc != viewingItem.lsDoc %}
                                        <span class="badge badge-default">{{ item.lsDoc.title|u.truncate(30) }}</span>
                                    {% endif %}
                                    {% block end_of_item_a '' %}
                                </a>
                            {% elseif association.destinationLsDoc is not empty %}
                                {% set doc = association.destinationLsDoc %}
                                <a href="{{ path('editor_lsdoc', {'id':doc.id}) }}" data-doc-id="{{ doc.id }}" class="list-group-item lsdoc clearfix">
                                    Document: {{ doc.title }}
                                    {{ block('end_of_item_a') }}
                                </a>
                            {% elseif association.destinationNodeUri is not empty %}
                                {% set uri = association.destinationNodeUri %}
                                <span data-association-id="{{ association.id }}" class="list-group-item lsassociation lsitem-uri clearfix">
                                    {{ uri|local_remote_uri }}
                                    {{ block('end_of_item_a') }}
                                </span>
                            {% else %}
                                <span data-association-id="{{ association.id }}" class="list-group-item lsassociation lsitem-uri clearfix">
                                    {{ association.destinationNodeIdentifier }}
                                    {{ block('end_of_item_a') }}
                                </span>
                            {% endif %}
                        {% elseif association.destinationLsDoc is defined %}
                            {% set doc = association %}
                            <a href="{{ path('editor_lsdoc', {'id':doc.id}) }}" data-doc-id="{{ doc.id }}" class="list-group-item lsdoc clearfix">
                                Document: {{ doc.title }}
                                {{ block('end_of_item_a') }}
                            </a>
                        {% elseif association.isLsItem is defined %}
                            {% set item = association %}
                            <a href="{{ path('editor_lsitem', {'id':item.id}) }}" data-item-id="{{ item.id }}" class="list-group-item lsitem clearfix">
                                {% if item.humanCodingScheme is not empty %}
                                    {{ item.humanCodingScheme }}
                                {% endif %}
                                {% if item.fullStatement != item.humanCodingScheme %}
                                    {{ item.fullStatement }}
                                {% endif %}
                                {{ block('end_of_item_a') }}
                            </a>
                        {% elseif association.isLsDoc is defined %}
                            {% set doc = association %}
                            <a href="{{ path('editor_lsdoc', {'id':doc.id}) }}" data-doc-id="{{ doc.id }}" class="list-group-item lsdoc clearfix">
                                Document: {{ doc.title }}
                                {{ block('end_of_item_a') }}
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endif %}

core/templates/framework/editor/_ls_item_component.html.twig
{% if items is not empty %}
    <section class="card card-default card-component" id="item-component-{{ componentName }}">
        <div class="card-header">{{ title }}</div>
        <div class="card-body">
            <div>
                <div class="list-group">
                    {% for item in items %}
                        <a href="{{ path('editor_lsitem', {'id':item.id}) }}" data-item-id="{{ item.id }}" class="list-group-item lsitem clearfix">
                            {% if item.humanCodingScheme is not empty %}
                                <span class="item-humanCodingScheme">{{ item.humanCodingScheme }}</span>
                            {% endif %}
                            {% if item.shortStatement != item.humanCodingScheme %}
                                {{ item.shortStatement }}
                            {% endif %}
                            {% block end_of_item_a '' %}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endif %}

core/templates/framework/editor/_modal_component.html.twig
{% if closeButton is not defined %}
    {% set closeButton = 'Close' %}
{% endif %}
{% if saveButton is not defined %}
    {% set saveButton = 'Save' %}
{% endif %}
<div class="modal fade" id="{{ modalName }}Modal" tabindex="-1" role="dialog" aria-labelledby="{{ modalName }}ModalLabel">
    <div class="modal-dialog modal-{{ modalSize|default('xl') }}" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="{{ modalName }}ModalLabel">{{ modalTitle }}</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% block modalBody %}Loading form...{% endblock %}
            </div>
            <div class="modal-footer">
                {% block modalAllButtons %}
                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">{{ closeButton }}</button>
                    {% block modalButtons %}
                        <button type="button" class="btn btn-primary btn-save">{{ saveButton }}</button>
                    {% endblock %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

core/templates/framework/editor/render_child.html.twig
<li>
    <a href="{{ lsItem.uri|local_uri }}" name="mark-{{ lsItem.id }}" class="lsItem text-muted">
        {%- if lsItem.humanCodingScheme is not empty %}<span class="item-humanCodingScheme">{{ lsItem.humanCodingScheme }}</span> {% endif -%}
        {% if lsItem.fullStatement != lsItem.humanCodingScheme %}{{ lsItem.fullStatement -}}{% endif -%}
    </a>
    <ul>
    {% for childWithId in lsItem.children %}
        {% set child = items[childWithId.id] %}
        {% include 'framework/editor/render_child.html.twig' with { 'lsItem':child, 'lsDoc':lsDoc, 'items':items, 'highlight':highlight} %}
    {% endfor %}
    </ul>
</li>

core/templates/framework/editor/render_child.json.twig
{
    "title":{{ lsItem.fullStatement|json_encode|raw }},
    "humanCoding":{{ lsItem.humanCodingScheme|json_encode|raw }},
    "key":{{ lsItem.id|json_encode|raw }}
    {% if lsItem.children is not empty %}
        , "folder": true, "expanded": true, "children": [
            {% for childWithId in lsItem.children %}
                {% if not loop.first %}, {% endif %}
                {% set child = items[childWithId.id] %}
                {% include 'framework/editor/render_child.json.twig' with { 'lsItem':child, 'lsDoc':lsDoc, 'items':items, 'highlight':null} %}
            {% endfor %}
        ]
    {% endif %}
}

core/templates/framework/editor/render_document.html.twig
<h3>
    <a href="{{ lsDoc.uri|local_uri }}" name="document" class="lsDoc text-muted">
        {{ lsDoc.title }}
    </a>
</h3>
<ul>
    {% for itemId in topItemIds %}
        {% set item = items[itemId] %}
        {% include 'framework/editor/render_child.html.twig' with { 'lsItem':item, 'lsDoc':lsDoc, 'items':items, 'highlight':highlight } %}
    {% endfor %}

    {% if orphaned is not empty %}
        <li>
            <strong>Orphaned</strong>:
            <ul>
                {% for item in orphaned %}
                    {% include 'framework/editor/render_child.html.twig' with { 'lsItem':item, 'lsDoc':lsDoc, 'items':items, 'highlight':highlight } %}
                {% endfor %}
            </ul>
        </li>
    {% endif %}
</ul>

core/templates/framework/editor/render_document.json.twig
{% set mainChildren = (topItemIds is not empty) %}
[
    {
        "title": {{ lsDoc.title|json_encode|raw }},
        "key": "doc-{{ lsDoc.id|raw }}",
        "folder": true, "expanded": true, "children": [
            {% for itemId in topItemIds %}
                {% if not loop.first %}, {% endif %}
                {% set item = items[itemId] %}
                {% include 'framework/editor/render_child.json.twig' with { 'lsItem':item, 'lsDoc':lsDoc, 'items':items, 'highlight':null } %}
            {% endfor %}
            {% if orphaned is not empty %}
                {% if mainChildren %}, {% endif %}
                {% for item in orphaned %}
                    {% if not loop.first %}, {% endif %}
                    {% include 'framework/editor/render_child.json.twig' with { 'lsItem':item, 'lsDoc':lsDoc, 'items':items, 'highlight':null } %}
                {% endfor %}
            {% endif %}
        ]
    }
]